#spring:
# datasource:
# username:root
# password:examly
# url:jdbc:mysql://localhost:3306/abacus
# driver-class-name:com.mysql.cj.jdbc.Driver
#jpa:
# show-sql:true
# hibernate:
#  ddl-auto:update
# properties:hibernate.dialect:org.hibernate.dialect.MySQL57Dialect

